"""Classe Icones

Classe qui définit les icônes utilisées pour les conditions climatiques.
"""

from enum import Enum

class Icones(Enum):
    """Enumération des icônes pour les conditions climatiques."""
    ICONE_00 = "assets/icones/clear-day.svg"
    ICONE_01 = "assets/icones/cloudy-1-day.svg"
    ICONE_02 = "assets/icones/cloudy-2-day.svg"
    ICONE_03 = "assets/icones/cloudy-3-day.svg"
    ICONE_06 = "assets/icones/rainy-1-day.svg"
    ICONE_07 = "assets/icones/rain-and-snow-mix.svg"
    ICONE_08 = "assets/icones/snowy-1-day.svg"
    ICONE_10 = "assets/icones/cloudy.svg"
    ICONE_11 = "assets/icones/rainy-1.svg"
    ICONE_12 = "assets/icones/rainy-2.svg"
    ICONE_13 = "assets/icones/rainy-3.svg"
    ICONE_14 = "assets/icones/rain-and-sleet-mix.svg"
    ICONE_15 = "assets/icones/rain-and-snow-mix.svg"
    ICONE_16 = "assets/icones/snowy-1.svg"
    ICONE_17 = "assets/icones/snowy-2.svg"
    ICONE_18 = "assets/icones/snowy-3.svg"
    ICONE_19 = "assets/icones/scattered-thunderstorms-day.svg"
    ICONE_23 = "assets/icones/fog.svg"
    ICONE_24 = "assets/icones/fog.svg"
    ICONE_25 = "assets/icones/wind.svg"
    ICONE_26 = "assets/icones/frost.svg"
    ICONE_27 = "assets/icones/hail.svg"
    ICONE_28 = "assets/icones/hail.svg"
    ICONE_30 = "assets/icones/clear-night.svg"
    ICONE_31 = "assets/icones/cloudy-1-night.svg"
    ICONE_32 = "assets/icones/cloudy-2-night.svg"
    ICONE_33 = "assets/icones/cloudy-3-night.svg"
    ICONE_36 = "assets/icones/rainy-1-night.svg"
    ICONE_37 = "assets/icones/rain-and-snow-mix.svg"
    ICONE_38 = "assets/icones/snowy-1-night.svg"
    ICONE_39 = "assets/icones/scattered-thunderstorms-night.svg"
    ICONE_40 = "assets/icones/wind.svg"
    ICONE_41 = "assets/icones/wind.svg"
    ICONE_42 = "assets/icones/tornado.svg"
    ICONE_43 = "assets/icones/wind.svg"
    ICONE_44 = "assets/icones/haze.svg"
    ICONE_45 = "assets/icones/dust.svg"
    ICONE_46 = "assets/icones/severe-thunderstorm.svg"
    ICONE_47 = "assets/icones/severe-thunderstorm.svg"
    ICONE_48 = "assets/icones/tornado.svg"
