"""Classe Icones

Classe qui définit les icônes utilisées pour les conditions climatiques.
"""

from enum import Enum

class Icones(Enum):
    """Enumération des icônes pour les conditions climatiques."""
    ICONE_00 = "icones/clear-day.svg"
    ICONE_01 = "icones/cloudy-1-day.svg"
    ICONE_02 = "icones/cloudy-2-day.svg"
    ICONE_03 = "icones/cloudy-3-day.svg"
    ICONE_04 = "icones/cloudy-1-day.svg"
    ICONE_05 = "icones/cloudy-1-day.svg"
    ICONE_06 = "icones/rainy-1-day.svg"
    ICONE_07 = "icones/rain-and-snow-mix.svg"
    ICONE_08 = "icones/snowy-1-day.svg"
    ICONE_09 = "icones/scattered-thunderstorms-day.svg"
    ICONE_10 = "icones/cloudy.svg"
    ICONE_11 = "icones/rainy-1.svg"
    ICONE_12 = "icones/rainy-2.svg"
    ICONE_13 = "icones/rainy-3.svg"
    ICONE_14 = "icones/rain-and-sleet-mix.svg"
    ICONE_15 = "icones/rain-and-snow-mix.svg"
    ICONE_16 = "icones/snowy-1.svg"
    ICONE_17 = "icones/snowy-2.svg"
    ICONE_18 = "icones/snowy-3.svg"
    ICONE_19 = "icones/scattered-thunderstorms-day.svg"
    ICONE_22 = "icones/cloudy-1-day.svg"
    ICONE_23 = "icones/fog.svg"
    ICONE_24 = "icones/fog.svg"
    ICONE_25 = "icones/wind.svg"
    ICONE_26 = "icones/frost.svg"
    ICONE_27 = "icones/hail.svg"
    ICONE_28 = "icones/hail.svg"
    ICONE_29 = ""
    ICONE_30 = "icones/clear-night.svg"
    ICONE_31 = "icones/cloudy-1-night.svg"
    ICONE_32 = "icones/cloudy-2-night.svg"
    ICONE_33 = "icones/cloudy-3-night.svg"
    ICONE_34 = "icones/cloudy-1-night.svg"
    ICONE_35 = "icones/cloudy-1-night.svg"
    ICONE_36 = "icones/rainy-1-night.svg"
    ICONE_37 = "icones/rain-and-snow-mix.svg"
    ICONE_38 = "icones/snowy-1-night.svg"
    ICONE_39 = "icones/scattered-thunderstorms-night.svg"
    ICONE_40 = "icones/wind.svg"
    ICONE_41 = "icones/wind.svg"
    ICONE_42 = "icones/tornado.svg"
    ICONE_43 = "icones/wind.svg"
    ICONE_44 = "icones/haze.svg"
    ICONE_45 = "icones/dust.svg"
    ICONE_46 = "icones/severe-thunderstorm.svg"
    ICONE_47 = "icones/severe-thunderstorm.svg"
    ICONE_48 = "icones/tornado.svg"
